language: go

go:
  - 1.6.3
  - 1.7.3
  - tip

install:
  - go get -v -t ./...

script:
  - go vet ./...
  - go test -v -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
